version: '3'

services:
    db:
        image: neo4j:4.1.2
        ports:
            - "7474:7474" 
            - "7687:7687"
        expose: 
            - "7474"
            - "7687"
        environment:
            NEO4J_AUTH: neo4j/root 